### ISSUE TITLE
Duplicate ID

### ISSUE THREAD

**Issue by jrock2004** [lstrrs/ember-line-clamp#44]
I have an array of services that uses <LineClamp /> and the more href has the same ID. `line-clamp-show-more-button`. I am using version `2.0.0`.

**Comment by bertdeblock** [comment]
Same goes for the `line-clamp-show-less-button` id. Are there any plans on addressing this issue? Rendering the same component multiple times is not an uncommon thing to do.

I'm open to making a PR for this as well.

**Comment by drewlee** [comment]
Including multiple instances of the same ID throughout a web page is problematic for accessibility, especially if the elements need to be referenced by ARIA attributes such as `aria-labelledby` and `aria-controls`. We should generate unique IDs for each instance of `ember-line-clamp` on the page and/or provide the ability to specify custom ID values. Currently, usage of this addon gets flagged as an a11y violation by axe-core's [duplicate-id-active](https://dequeuniversity.com/rules/axe/4.6/duplicate-id-active) check.

**Comment by lstrrs** [comment]
Fixed by https://github.com/lstrrs/ember-line-clamp/pull/95
